### ISSUE TITLE
Why this parameter order?

### ISSUE THREAD

**Issue by juanpide** [xiaodaigh/FastGroupBy.jl#8]
Why did you decide to use this order for the parameters
` fastby(sum, byvec, valvec)`
and not
` fastby(sum, valvec, byvec)`
?

R and other languages use the second approach.

**Comment by xiaodaigh** [comment]
Thanks for you question. But that is the order in DataFrames.jl's `by`. When I think of this problem I think of the `byvec` first as well, and that's how dplyr works as well where you specify `group_by` first before `summarize`. SQL puts `group_by` last but that's an arbitrary choice.
